[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "cd client && NPM_CONFIG_PRODUCTION=false npm install"
]

[phases.build]
cmds = [
  "cd client && npm run build"
]

[start]
cmd = "cd server && npm start"

